### ISSUE TITLE
Data description and questions

### ISSUE THREAD

**Issue by huizezhang-sherry** [etc5521-2020/assignment-1-koala#1]
Good work on getting the assignment rolling and I like your interactive table styling.

You need to fill in the introduction and motivation section. Think about why do you think energy consumption is an important and interesting topic to spend time working on? You can also talk about Europe's share of energy consumption relative to the world's. 

Question one can be expanded further with more details of what do you main by "the highest production". Is it the highest total production, import/export, or production by the type of energy?

In your last two questions, you mentioned analysing the trend in energy usage/ sustainable vs. non-sustainable energy production. I would be concerned given only three years of data is provided by tidytuesday. Of cause, you can grab more data from the Eurostat website, but you need to decide if you want to source more data or change the research question.

**Comment by whysptra** [comment]
Thanks for the feedback sherry
